version: "3"

services: 
  node-exporter:
    image: quay.io/prometheus/node-exporter
    volumes:
      - "/proc:/host/proc"
      - "/sys:/host/sys"
      - "/:/rootfs"
    command:
      - "-collector.procfs=/host/proc"
      - "-collector.sysfs=/host/sys"
      - "-collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)"
    ports:
      - "9100:9100"

